// CONFIG
export const GET_SCREEN_SIZE = 'GET_SCREEN_SIZE';

//ACCOUNT
export const ACCOUNT_AUTH_LOGIN = 'ACCOUNT_AUTH_LOGIN';
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';
export const ACCOUNT_CHECK_AUTH_TIMEOUT = 'ACCOUNT_CHECK_AUTH_TIMEOUT';
export const ACCOUNT_FORGOTTEN_PASSWORD = 'ACCOUNT_FORGOTTEN_PASSWORD';
export const ACCOUNT_FORGOTTEN_PASSWORD_REQUEST_SENT =
  'ACCOUNT_FORGOTTEN_PASSWORD_REQUEST_SENT';
export const ACCOUNT_RESET_PASSWORD = 'ACCOUNT_RESET_PASSWORD';
export const ACCOUNT_RESET_PASSWORD_REQUEST_SENT =
  'ACCOUNT_RESET_PASSWORD_REQUEST_SENT';
export const ACCOUNT_AUTH_REGISTER = 'ACCOUNT_AUTH_REGISTER';
export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAIL = 'ACCOUNT_REGISTER_FAIL';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const ACCOUNT_LOGOUT_COMPLETE = 'ACCOUNT_LOGOUT_COMPLETE';
export const ACCOUNT_CHECK_STATE = 'ACCOUNT_CHECK_STATE';
