// CONFIG
export const GET_SCREEN_SIZE = 'GET_SCREEN_SIZE';
export const SHOW_MODAL = 'SHOW_MODAL';

//ACCOUNT
export const ACCOUNT_AUTH_LOGIN = 'ACCOUNT_AUTH_LOGIN';
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';
export const ACCOUNT_CHECK_AUTH_TIMEOUT = 'ACCOUNT_CHECK_AUTH_TIMEOUT';
export const ACCOUNT_FORGOTTEN_PASSWORD = 'ACCOUNT_FORGOTTEN_PASSWORD';
export const ACCOUNT_FORGOTTEN_PASSWORD_REQUEST_SENT =
  'ACCOUNT_FORGOTTEN_PASSWORD_REQUEST_SENT';
export const ACCOUNT_RESET_PASSWORD = 'ACCOUNT_RESET_PASSWORD';
export const ACCOUNT_RESET_PASSWORD_REQUEST_SENT =
  'ACCOUNT_RESET_PASSWORD_REQUEST_SENT';
export const ACCOUNT_AUTH_REGISTER = 'ACCOUNT_AUTH_REGISTER';
export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAIL = 'ACCOUNT_REGISTER_FAIL';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const ACCOUNT_LOGOUT_COMPLETE = 'ACCOUNT_LOGOUT_COMPLETE';
export const ACCOUNT_CHECK_STATE = 'ACCOUNT_CHECK_STATE';
export const ACCOUNT_UPDATE_SAVED_ADDRESS = 'ACCOUNT_UPDATE_SAVED_ADDRESS';

//BASKET
export const INITIAL_BASKET = 'INITIAL_BASKET';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const CHANGE_BASKET_QTY = 'CHANGE_BASKET_QTY';
export const REMOVE_BASKET_SKU = 'REMOVE_BASKET_SKU';

//VOUCHER
export const CHECK_VOUCHER_CODE = 'CHECK_VOUCHER_CODE';
export const CHECK_AUTO_VOUCHER_CODES = 'CHECK_AUTO_VOUCHER_CODES';
export const ACCEPT_VOUCHER_CODE = 'ACCEPT_VOUCHER_CODE';
export const REJECT_VOUCHER_CODE = 'REJECT_VOUCHER_CODE';
export const REMOVE_VOUCHER_CODE = 'REMOVE_VOUCHER_CODE';
